### PR TITLE
Add explosion intensity

### PR DESCRIPTION
**Pull request by MT-Modder**
Regarding the changes made around line #1588:
This allows modders to change the intensity within the mob definition. (So it's not always 1)
^^^ Only applies to "explode" type attacks of course.

### CODE REVIEW

**Comment by tenplus1** [comment]
Added with changes.

**Comment by MT-Modder** [comment]
Are you still working on it? Because intensity is never passed to the on_blast callback with your changes and that was the whole point. That way modders can define whether or not mobs are strong enough to destroy nodes with this callback. I like the radius api changes though. :+1:

**Comment by tenplus1** [comment]
If I add blast intensity to the on_blast call then it will return a blast area a lot larger than intented as on_blast works it's way through each and every node in the original blast area already, so if a node inside that original area calls for a larger on_blast of it's own then it'll still work fine.

**Comment by MT-Modder** [comment]
Okay I didn't think of that.

**Pull request closed without merging**
