### PR TITLE
Jump now make mobs climb, and now mobs avoid water.

### PR DESCRIPTION
**Pull request by melzua**

### CODE REVIEW

**Comment by 0-afflatus** [comment]
:+1:

**Comment by Ombridride** [comment]
Great improve, when monsters are agressive and when they follow you because they want to damage you, they avoid water or not ?

**Comment by melzua** [comment]
They shouldn't. I only modified the code when self.state == walk, so when they are lazy walking around :-)

**Comment by Ombridride** [comment]
Ok, perfect ! +1

**Comment by tenplus1** [comment]
Added, thanks :)

**Pull request closed without merging**
