### PR TITLE
sharper and more default game textures

### PR DESCRIPTION
**Pull request by JurajVajda**
I had a quick look and edit on the current textures and sometimes they look more MC than MT and if they are MT then maybe from version 1.0 :) so i made:
* tree monster look more like the default tree from MT game and sharper - added
* dirt monster look more like the default dirt from MT game and sharper - added
* stone monster look more like the default stone from MT game and sharper - replaced
** since there was very small difference between the textures i replaced yours, but you can still use both if you like
* lava pick axe look more like the one from MT game
* added another cow texture

mobs_redo_textures
cow

### CODE REVIEW

**Comment by 0-afflatus** [comment]
Nice work! Personally I'd like to see these textures diverge more from MC, but I guess there is no harm in being a little conservative.

**Comment by JurajVajda** [comment]
added also another cow texture ;)

**Comment by tenplus1** [comment]
Added new cow texture, thank you :)

**Comment by JurajVajda** [comment]
ok sounds reasonable and thank you to ;)

**Pull request closed without merging**
